openapi: 3.0.0
info:
  title: Iconscout Plugin API v2.0 Docs
  version: '2.0'
  description: |-
    Iconscout is India's First Digital Goods marketplace. We are providing high quality digital assets accessible to everyone. We are bridging the gap between users and designers by connecting them on mutual platform. We are enabling designers to share their work to large audience out there and earn from what they love doing. By doing so, we are able to provide amazing resources to the users and right amount to our designers - our two most important stakeholders.

    Iconscout API provides developers an access to huge collection of graphic resources. Developers are free to utilize our API to develop apps, plugins, extensions and many more.

    Please follow our API docs for integration and do drop us mail in case of any queries.
  contact:
    name: Arpan Rank
    email: arpan@iconscout.com
  termsOfService: 'https://iconscout.com/legal/terms-of-use'
servers:
  - url: 'https://api.iconscout.com'
paths:
  /v2/search:
    get:
      summary: Search
      tags: []
      operationId: get-v2-search
      parameters:
        - schema:
            type: string
          in: query
          name: query
          required: true
        - schema:
            type: string
            enum:
              - item
              - pack
            default: item
          in: query
          name: product_type
        - schema:
            type: string
            enum:
              - icon
              - illustration
              - photo
            default: icon
          in: query
          name: asset
        - schema:
            type: string
            enum:
              - premium
              - free
          in: query
          name: price
        - schema:
            type: number
            default: 10
          in: query
          name: per_page
        - schema:
            type: number
            default: 1
          in: query
          name: page
        - schema:
            type: array
            items:
              type: string
              enum:
                - svg
                - eps
                - ai
                - png
                - jpg
            uniqueItems: true
          in: query
          name: 'formats[]'
          description: ''
        - schema:
            type: string
            default: relevant
            enum:
              - relevant
              - popular
              - latest
              - color
          in: query
          name: sort
        - schema:
            type: boolean
            default: 'false'
          in: query
          name: quality
      description: It returns a list with all the assets according to the search.
    parameters: []
  '/v2/items/{item}':
    parameters:
      - schema:
          type: string
        name: item
        in: path
        required: true
        description: It can be uuid or slug of item.
    get:
      summary: Fetch Item
      tags: []
      operationId: get-v2-items-slug
      description: It gives you detailed information about an item.
      parameters: []
  '/v2/items/{item}/available-styles':
    parameters:
      - schema:
          type: string
        name: item
        in: path
        required: true
        description: It can be uuid or slug of item.
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-v2-items-item-available-styles
      description: It gives you available styles of an item.
  '/v2/items/{item}/available-relations':
    parameters:
      - schema:
          type: string
        name: item
        in: path
        required: true
        description: It can be uuid or slug of item.
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-v2-items-item-available-relations
      description: |-
        It gives you available relations of an item.
        - contributor
        - pack
        - bundle
  '/v2/items/{uuid}/api-download':
    parameters:
      - schema:
          type: string
        name: uuid
        in: path
        required: true
        description: Here you need to pass uuid of item.
    post:
      summary: Item Download
      tags: []
      operationId: post-v2-items-uuid-api-download
      parameters:
        - schema:
            type: string
            default: 9c65f0d3b0aa27ca5a8215b0050eba0c
          in: header
          name: Client-Secret
          required: true
          description: Drop mail on arpan@iconscout.com to get new Client-Secret.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              Item Download Format:
                value:
                  format: svg
        description: Here you need to pass `format` of item to download (available from fetch item api)
      description: Get download link of particular item
  /v2/collections:
    get:
      summary: Your GET endpoint
      tags: []
      operationId: get-v2-collections
      description: It gives you a list with the featured collections by our experts available at Iconscout.
  '/v2/collections/{collection}':
    parameters:
      - schema:
          type: string
        name: collection
        in: path
        required: true
        description: It can be uuid or slug of collection.
    get:
      summary: Your GET endpoint
      tags: []
      operationId: get-v2-collections-slug
      description: It gives you detailed information about the collection.
components:
  schemas: {}
  securitySchemes: {}
